// Code generated by "stringer -type=logLevel"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug-0]
	_ = x[Info-1]
	_ = x[Warn-2]
	_ = x[Error-3]
	_ = x[Fatal-4]
}

const _logLevel_name = "DebugInfoWarnErrorFatal"

var _logLevel_index = [...]uint8{0, 5, 9, 13, 18, 23}

func (i logLevel) String() string {
	if i < 0 || i >= logLevel(len(_logLevel_index)-1) {
		return "logLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _logLevel_name[_logLevel_index[i]:_logLevel_index[i+1]]
}
